title: Gabriel Sandoval
logo: /assets/img/headshot.jpg
description: I am a graduating senior at UC Berkeley studying Data Science, with interests in data analysis, machine learning, and artificial intelligence. I am currently seeking opportunities that are open to contract work.
# show_downloads: true
theme: jekyll-theme-minimal
